### ISSUE TITLE
HomeAssistant logs - 'will be removed...' 

### ISSUE THREAD

**Issue by Ursli71** [Rudd-O/homeassistant-meteoswiss#45] opened 2024-06-26 13:08 UTC
hi there,
Thanks for the great Swiss Meteo integration! 

I get a couple of log notifications that the integration needs update given HA Core adjustments.  See below:

1)
Logger: homeassistant.helpers.typing
Quelle: helpers/deprecation.py:197
Erstmals aufgetreten: 14:56:09 (1 Vorkommnisse)
Zuletzt protokolliert: 14:56:09

HomeAssistantType was used from meteoswiss, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'meteoswiss' custom integration

2)
Logger: homeassistant.components.sensor.const
Quelle: helpers/deprecation.py:197
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 15:01:26 (1 Vorkommnisse)
Zuletzt protokolliert: 15:01:26

STATE_CLASS_MEASUREMENT was used from meteoswiss, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please report it to the author of the 'meteoswiss' custom integration

and 3)
Logger: homeassistant.const
Quelle: helpers/deprecation.py:197
Erstmals aufgetreten: 15:01:24 (8 Vorkommnisse)
Zuletzt protokolliert: 15:01:26

IRRADIATION_WATTS_PER_SQUARE_METER was used from meteoswiss, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfIrradiance.WATTS_PER_SQUARE_METER instead, please report it to the author of the 'meteoswiss' custom integration
PRESSURE_HPA was used from meteoswiss, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.HPA instead, please report it to the author of the 'meteoswiss' custom integration
SPEED_KILOMETERS_PER_HOUR was used from meteoswiss, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.KILOMETERS_PER_HOUR instead, please report it to the author of the 'meteoswiss' custom integration
TEMP_CELSIUS was used from meteoswiss, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'meteoswiss' custom integration
TIME_MINUTES was used from meteoswiss, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.MINUTES instead, please report it to the author of the 'meteoswiss' custom integration

Thanks for working on the update so that we will be able to continue to use this great integration. 

Cheers, Urs

**Comment by braetkuegeli** [comment] 2024-07-07 06:34
Duplicate of #34

**Comment by Rudd-O** [comment] 2024-08-23 14:28
A pull request has been filed by a great collaborator that fixes it, and I have merged it.

**Closed by Rudd-O** 2024-08-23 14:28 UTC
