### ISSUE TITLE
HomeAssistantType was used from meteoswiss, this is a deprecated alias which will be removed in HA Core 2025.5

### ISSUE THREAD

**Issue by tluethi71** [Rudd-O/homeassistant-meteoswiss#42] opened 2024-05-08 12:23 UTC
I got this message:

Logger: homeassistant.helpers.typing
Quelle: helpers/deprecation.py:206
Erstmals aufgetreten: 11:45:53 (1 Vorkommnisse)
Zuletzt protokolliert: 11:45:53

HomeAssistantType was used from meteoswiss, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'meteoswiss' custom integration

**Comment by tluethi71** [comment] 2024-05-08 12:48
and there is one more upon start up of HA:

Logger: homeassistant.const
Quelle: helpers/deprecation.py:206
Erstmals aufgetreten: 14:46:37 (8 Vorkommnisse)
Zuletzt protokolliert: 14:46:38

IRRADIATION_WATTS_PER_SQUARE_METER was used from meteoswiss, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfIrradiance.WATTS_PER_SQUARE_METER instead, please report it to the author of the 'meteoswiss' custom integration
PRESSURE_HPA was used from meteoswiss, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.HPA instead, please report it to the author of the 'meteoswiss' custom integration
SPEED_KILOMETERS_PER_HOUR was used from meteoswiss, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.KILOMETERS_PER_HOUR instead, please report it to the author of the 'meteoswiss' custom integration
TEMP_CELSIUS was used from meteoswiss, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'meteoswiss' custom integration
TIME_MINUTES was used from meteoswiss, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.MINUTES instead, please report it to the author of the 'meteoswiss' custom integration

**Comment by braetkuegeli** [comment] 2024-07-07 06:34
Duplicate of #34

**Comment by Rudd-O** [comment] 2024-08-23 18:06
Fixed.

**Closed by Rudd-O** 2024-08-23 18:06 UTC
